# This workflow will build, run tests and create the archive to generate a version from the Package

name: Archive

on:
  push:
    tags:
      - 'v*'

jobs:
  archive:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Archive
        run: ./FrameworkCreator.sh

      - name: Set enviroment for github-release
        run: |
          echo ::set-env name=RELEASE_TAG::"GITHUB_REF_NAME"
          echo ::set-env name=RELEASE_NAME::"$GITHUB_WORKFLOW"

      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          files: MiniService.xcframework
