# This workflow will build, run tests and create the archive to generate a version from the Package

name: Archive

on:
  push:
    tags:
      - 'v*'

jobs:
  archive:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Archive
        run: ./FrameworkCreator.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GH }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GH }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: MiniService.zip
          asset_name: MiniService.zip
          asset_content_type: application/zip
