# This workflow will build, run tests and create the archive to generate a version from the Package

name: Archive

on:
  push:
    tags:
      - 'v*'

jobs:
  archive:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Archive
        run: ./FrameworkCreator.sh