# This workflow will build, run tests and create the archive to generate a version from the Package

name: Archive

on:
  push:
    tags:
      - 'v*'

jobs:
  archive:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Archive
        run: ./FrameworkCreator.sh
      - uses: actions/upload-artifact@v2
        with:
          name: MiniService.zip
          path: ./MiniService.zip

  release:
    needs: archive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: MiniService.zip
      - name: Show files
        run: "ls -lah"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
              
      - name: Upload Release Asset
        id: upload_release_asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MiniService.zip
          asset_name: MiniService.zip
          asset_content_type: application/zip