# This workflow will build, run tests and create the archive to generate a version from the Package

name: Version

on:
  push:
    tags:
      - v**

jobs:
  build:

    runs-on: macos-latest
    permissions:
      contents: wrhite
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  archive:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Archive
        run: ./FrameworkCreator.sh

  release:

    runs-on: ubuntu-latest
    permissions:
      contents: wrhite
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "MiniService.xcframework"
